project:
  type: website

website:
  title: "Tá, mas e a economia?"
  favicon: imagens/logo_fav.ico
  navbar:
    logo: imagens/logo_aex.png
    background: "#223a52"
    foreground: "white"
    right:
      - text: "Início"
        href: index.qmd
      - text: "Newsletter"
        file: Newsletter/indexNe.qmd
      - text: "Quem somos?"
        href: sobre.qmd
      - text: "Receba no email"
        href: email.qmd
      - icon: instagram
        href: https://www.instagram.com/tamaseaeconomia
        aria-label: Instagram
  page-footer:
    background: "#223a52"
    left: |
      Site desenvolvido por 
      <a href="https://www.linkedin.com/in/paula-oliveira-431271220/" style="color: white; text-decoration: none;">
        Paula Leandra <i class="bi bi-linkedin"></i>
      </a> 
       e 
      <a href="https://www.linkedin.com/in/jonathan-cunha-78bb0b28b/" style="color: white; text-decoration: none;">
        Jonathan Cunha <i class="bi bi-linkedin"></i>
      </a>
    right: "2026 Tá, mas e a economia?"

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: false
    lang: pt-BR
    date-format: "DD/MM/YYYY"
    labels:
      author: Autor
      published: Publicado em

editor: visual

