---
title: "Estamos vivenciando o fim da hegemonia do dólar?"
author:
  - Manuela Marangoni Jampani, 3° semestre de economia e Gustavo Lima Moraes, 7° semestre de economia.
date: 2026-03-16
description: Nos últimos meses, o dólar tem sofrido ameaças por outros países em eliminar o seu uso como intermediária para trocas bilaterais. Mas quais as causas dessa mudança após 80 anos de hegemonia?
format:
  html:
    toc: false
    css: styles.css
---

O funcionamento da economia da forma que conhecemos se fundamenta a partir de um princípio que muitas vezes passa despercebido para a maioria das pessoas: a confiança sobre o valor da moeda utilizada como meio de troca. Para manter essa confiabilidade garantida nas trocas internacionais, as instituições financeiras do século XIX estabeleceram a conversibilidade da moeda em ouro, visto que é atribuído ao minério um valor intrínseco pelos indivíduos. Ao longo do século seguinte, alguns episódios históricos produziram mudanças nessa característica da moeda, fazendo com que ela se transformasse em moeda fiduciária.

### 

::: caixinha-lateral-esq
**“Tá, mas e a Economia? - FUNÇÕES DA MOEDA**

Existem três funções essenciais da moeda em uma economia:

1.  Meio de troca, ao intermediar transações e substituir a necessidade da prática do escambo.

2.  Unidade de conta, ao servir de padrão comum para a mensuração e comparação de valores.

3.  Reserva de valor, ao permitir a transferência de poder de compra ao longo do tempo, ainda que de forma imperfeita frente a algum nível de inflação.
:::

**Contexto histórico**

Historicamente, a economia global era sustentada pelo padrão-ouro, um sistema rígido em que o valor das moedas dependia das reservas físicas do metal. No entanto, esse regime impunha uma barreira à emissão de moeda pelos governos, que eram obrigados a ignorar crises sociais e o desemprego para manter suas reservas de ouro intactas. Com a Primeira Guerra Mundial, a necessidade de impressão de dinheiro para financiar os custos do conflito colocaram o sistema em colapso, levando as nações a buscarem outras alternativas para retomar a estabilidade financeira. O problema se torna ainda mais acentuado com a Crise de 1929 e a Segunda Guerra Mundial, quando o padrão-ouro limitou a flexibilidade da política monetária ao impedir que os governos emitissem dinheiro para diminuir a taxa de juros, já que precisavam manter suas reservas de metal o mais estável possível. Esse cenário de desemprego em massa e colapso social provou que o ouro havia se tornado um sistema obsoleto, que impedia a administração econômica mais dinâmica exigida pelo mundo moderno. Nesse cenário, o Acordo de Bretton Woods (1944) buscou amenizar o problema com a criação do padrão dólar-ouro. Visto que os Estados Unidos detinham três quartos das reservas mundiais de ouro, a moeda americana ficou definida como o norte da economia mundial, sendo a única divisa diretamente conversível em ouro, enquanto as outras se vinculavam ao dólar.

::: caixinha-lateral-dir
**“Tá, mas e a Economia? - Padrão-Ouro**

O padrão-ouro foi um sistema monetário de lastro físico e câmbio fixo estruturado sobre três regras fundamentais: cada governo definia o valor da sua moeda em relação a uma quantidade específica de ouro, o que estabelecia automaticamente uma equivalência fixa nas taxas de câmbio entre os países. Além disso, o sistema garantia a conversibilidade total do papel-moeda, que funcionava, na prática, como um recibo, possibilitando que qualquer indivíduo ou instituição solicitasse a troca de suas cédulas pela quantidade exata de ouro correspondente nos cofres públicos. Consequentemente, a oferta de dinheiro de um país era bastante limitada; um Banco Central só tinha autorização para imprimir novas notas se comprasse e armazenasse a quantidade equivalente de ouro físico nas suas reservas.
:::

Por fim,  o domínio do dólar se estabelece de fato na década de 1970, quando os EUA romperam o vínculo direto com o ouro, tornando a moeda puramente fiduciária. Para manter sua relevância global, os EUA firmaram acordos estratégicos para que o petróleo fosse comercializado exclusivamente em dólares, forçando os países a acumularem a moeda americana e criando uma demanda que permitiu aos EUA financiar sua própria economia com facilidade, dando início ao chamado padrão-dólar.

::: caixinha-lateral-esq
“Tá, mas e a Economia? - Moeda Fiduciária

Moeda fiduciária é o dinheiro emitido e regulado pelo governo que não possui valor intrínseco e não é lastreado por commodities físicas, como o ouro. Seu valor baseia-se na confiança do público na economia e na autoridade governamental.
:::

**O fim da era dólar**

A “desdolarização” da economia global tem ganhado cada vez mais espaço nas discussões internacionais, sendo protagonizada pelos países componentes do BRICS. Alguns membros do bloco já negociam entre si sem o uso do dólar, como é o caso da China, Rússia e Brasil, e projetam a criação de uma moeda comum para transações comerciais entre eles.

::: {callout-tip}
ODS 17 - Parcerias e meios de implementação

Quando países como Brasil, Rússia e China passam a negociar suas transações comerciais em outras moedas, eles ajudam a aumentar a estabilidade econômica global porque fortalecem alianças regionais e diminuem a sensibilidade de suas economias em relação a políticas financeiras e sanções dos Estados Unidos.
:::

Além disso, em um estudo publicado pelo banco norte-americano JP Morgan, a participação do dólar nas reservas cambiais dos bancos centrais atingiu o menor patamar das últimas duas décadas em paralelo com a influência macroeconômica da economia americana com base na participação do PIB e das exportações do país no montante global.

**Mas, mesmo após 80 anos, o que causa o fim dessa hegemonia?**

Existem três fatores principais que podem corroer o status do dólar. As políticas dos últimos governos americanos que utilizam sua moeda como instrumento para punição de transgressões na área geopolítica - com sanções econômicas e tarifas - encorajam certos atores que tentaram contornar a divisa americana para diminuir a dependência financeira do governo americano. As ofensivas tarifárias impostas pelo governo Donald Trump durante o ano de 2025 e, mais recentemente em 2026, ameaçam o futuro da globalização que teve o dólar como protagonista absoluto. Essa ameaça eleva a imprevisibilidade do governo americano e impacta um fator fundamental para a manutenção dessa moeda como reserva global: a percepção de segurança e a estabilidade da economia americana. A deterioração do caráter dos EUA como porto seguro global de investimentos diminui a confiança que os governos estrangeiros possuem no país e promove a diversificação de seus ativos em outras moedas para proteger a própria economia.

Além disso, o segundo fator que ameaça a hegemonia do dólar envolve os desenvolvimentos de outras economias globais que elevam a credibilidade de suas divisas como fonte de reserva. Declarações recentes do presidente chinês Xi Jinping defendem que o Renminbi se torne uma moeda de reserva global, sinalizando as crescentes ambições da China de desempenhar um papel maior no sistema financeiro internacional. Embora ainda carente da liquidez e acessibilidade exigidas pelos bancos centrais internacionais, o país asiático tem utilizado cada vez mais sua própria moeda na liquidação de transações comerciais transfronteiriças - o que poderá ser ainda mais acelerado com o yuan digital - cobrindo uma maior demanda global pelo Renminbi e aumentando a percepção de segurança e estabilidade na moeda.

Por fim, o crescente endividamento de países desenvolvidos como o próprio EUA não auxilia na retomada da confiança do domínio de sua moeda. No ano de 2025, o montante da dívida pública do país ultrapassou a marca de US\$ 38 trilhões, o equivalente a 125% de seu PIB, ao mesmo tempo em que o congresso norte-americano aprovou a lei fiscal “One Big Beautiful Act” que combina cortes profundos de impostos com um aumento nos gastos federais, com expectativas de aprofundamento ainda maior do problema. Esse cenário agrava a perspectiva de uma dívida insustentável, o que aumenta a probabilidade de uma inflação mais alta como forma de inadimplência, acelerando a fragmentação financeira internacional.

**O que esperar com o fim dessa era?**

Fundamentalmente, a desdolarização poderia alterar o equilíbrio de poder entre os países, o que, por sua vez, poderia remodelar a economia e os mercados globais. O mercado mais impactado seria, com certeza, o próprio EUA, onde este movimento levaria a uma depreciação generalizada da moeda e a um desempenho inferior dos ativos financeiros americanos em comparação com o resto do mundo. Como consequência direta, estes impactos levarão à realocação de recursos para mercados mais atrativos fora dos EUA, causando uma forte pressão de alta sobre os rendimentos reais para compensar o desinvestimento.

Sendo assim, o fenômeno histórico é um marco simbólico da ruptura da ordem mundial unipolar americana conhecida nas últimas décadas, e o início de um novo sistema político e financeiro que fragmenta, segundo o olhar de alguns especialistas, os países em grandes zonas de influência. Segundo Faria (2026), com a ascensão de uma organização mundial multipolarizada, o Brasil pode exercer um papel importante neste cenário ao ser indiscutivelmente a principal economia do hemisfério sul. No entanto, esse protagonismo irá depender sobretudo pelo sucesso em liderar regionalmente a América Latina e na criação de um desejo de fortalecimento da sua autonomia, garantindo ao país a transição de economia periférica para um patamar de influência global.

**Para saber mais:**

FARIA, L. CHANGING PLACE: THE NEW INTERNATIONAL ORDER AND BRAZIL. Brazilian Journal of Strategy & International Relations e-ISSN 2238-6912 \| v.14, n.28, Jul./Dec. 2025 \| p.47-65

DE-DOLLARIZATION: IS THE US DOLLAR LOSING ITS DOMINANCE? J.P. Morgan. Jul. 2025. Disponível em: www.jpmorgan.com/insights/global-research/currencies/de-dollarization

**Transparência em Uso de IA**

Nome da ferramenta: Google Gemini Pro

Finalidade do uso: correção de erros gramaticais e para garantir maior clareza e precisão na explicação de termos técnicos.

O texto foi revisado pelos autores humanos que são responsáveis pelo conteúdo final.
